### ISSUE TITLE
Final docker image returns "Caused by: java.lang.NoClassDefFoundError: java/sql/SQLException"

### ISSUE THREAD

**Issue by bhatnagarm** [bhatnagarm/helloworld#6]
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:86)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer
        at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:437)
        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:419)
        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:412)
        at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:268)
        at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:249)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202)
        at com.example.helloworld.HelloWorldApplication.main(HelloWorldApplication.java:12)
        ... 8 more
Caused by: java.lang.NoClassDefFoundError: java/sql/SQLException
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170)
        at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:433)
        ... 15 more
Caused by: java.lang.ClassNotFoundException: java.sql.SQLException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)

**Comment by bhatnagarm** [comment]
Could be missing module java.sql. Still need to try.

**Comment by bhatnagarm** [comment]
Adding module java.sql fixed the issue.
