### ISSUE TITLE
Issue with "Caused by: java.lang.ClassNotFoundException: javax.naming.NamingException"

### ISSUE THREAD

**Issue by bhatnagarm** [bhatnagarm/helloworld#7]
Issue with build

12:06:32.939 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.NoClassDefFoundError: javax/naming/NamingException
        at org.springframework.web.context.support.StandardServletEnvironment.customizePropertySources(StandardServletEnvironment.java:87)
        at org.springframework.core.env.AbstractEnvironment.<init>(AbstractEnvironment.java:124)
        at org.springframework.core.env.StandardEnvironment.<init>(StandardEnvironment.java:54)
        at org.springframework.web.context.support.StandardServletEnvironment.<init>(StandardServletEnvironment.java:45)
        at org.springframework.boot.SpringApplication.getOrCreateEnvironment(SpringApplication.java:449)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:338)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202)
        at com.example.helloworld.HelloWorldApplication.main(HelloWorldApplication.java:12)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:86)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.ClassNotFoundException: javax.naming.NamingException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 18 common frames omitted

**Comment by bhatnagarm** [comment]
Added java.naming fixed this.
